// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"4212ed9a73670a9c703e1a7e1faa102a3c4450dcf419c93c8b14bd6985222c3159c82c7c2c90e73265bcb6478d7deb844ac13c2202e96e8b86e1c70c284f7695"}}
];
